### PR TITLE
Integer version of validated FFT implementation, for debugging.

### PR DESCRIPTION
**Pull request by capn-freako**
Hi Conal,

I've taken the now validated code from _fft_test.hs_ and imported it into _TreeTest.hs_, converting from _Double_ to _Int_ along the way. As you already know, my attempt to compile this code ran for almost 24 hours and did not complete.

Thanks,
-db

### CODE REVIEW

**Comment by conal** [comment]
I've tried this example with rewrite logging turned on. I don't yet know what's causing the extra-long (probably infinite) compilation. However, I'm seeing that we'll need to handle some new primitives. We can add `rem` and `quot` on `Int`, but maybe instead support `Float` or `Double`. Would you like to help?

**Comment by capn-freako** [comment]
Yes, that’d be perfect. (I’ve been teetering on the edge of just diving in and attempting to add Double to your machinery.)

Thanks,
-db

**Comment by conal** [comment]
Great. I just added doc/adding-primitives.md as a starting point for describing how to add primitive operations and types. To prepare for `Double`, I generalized the numeric prims in commits https://github.com/conal/circat/commit/2df3192f69e546a02c94234f20c5782146f2d8dd and https://github.com/conal/lambda-ccc/commit/3dfac57de19adb99215fcd6c9b19bb7b443dad2e.

How about trying these instructions for adding `Double` and letting me know where they need more detail?

**Comment by capn-freako** [comment]
Will do.

**Pull request merged**
