### PR TITLE
FFT Computational Correctness Check - Almost Correct.

### PR DESCRIPTION
**Pull request by capn-freako**
Hi Conal,

I wanted to check the computational correctness of my latest attempt at "FFT, via butterfly".
So, I created a new file: *fft_test.hs*, for the purpose of checking this.
In applying the standard FFT test cases, I find that the computation seems correct, with the following exception:

In some cases, the first and last output elements appear to be swapped.

I'm wondering if you have any thoughts about what might be going on.

Thanks,
-db

### CODE REVIEW

**Comment by capn-freako** [comment]
Hi Conal,

Scratch that; there's more wrong than just a swap of the first and last elements.
You can see, in my last test case, that the actual output is completely missing an expected 90 degree phase shift of both its non-zero outputs.

Back to the drawing board. :-(

-db

**Comment by capn-freako** [comment]
It's working! (At least, for my 5 standard test cases. I still need to test thoroughly, with _QuickCheck_.)

Does the "&&&" operator have any hope of making it through your compiler?

I'm staring at line 49, in disbelief that the fundamental atomic computation at the heart of the DFT can be expressed so simply. It really is nothing more than the recursive application of a sum and a phased difference over deinterleaved sub-sets of the original input. That's really beautiful! Thanks for building this machinery, friend.

I think I'd like to clean up line 49 a little further, by combining "toP ... fromP" into a "inP" operator, as you've done with Pair and Transpose. Do you have any other suggestions for aesthetic improvement?

I'm really enjoying this. I hope you are, too.
-db

**Comment by capn-freako** [comment]
davids-air-2:test dbanas$ ./fft_test 

Testing input: [ 1.000 :+  0.000, 0.000 :+  0.000, 0.000 :+  0.000, 0.000 :+  0.000]
Expected output: [ 1.000 :+  0.000, 1.000 :+  0.000, 1.000 :+  0.000, 1.000 :+  0.000]
Actual output:   B (B (L ( 1.000 :+  0.000) :# L ( 1.000 :+  0.000)) :# B (L ( 1.000 :+  0.000) :# L ( 1.000 :+  0.000)))

Testing input: [ 1.000 :+  0.000, 1.000 :+  0.000, 1.000 :+  0.000, 1.000 :+  0.000]
Expected output: [ 4.000 :+  0.000, 0.000 :+  0.000, 0.000 :+  0.000, 0.000 :+  0.000]
Actual output:   B (B (L ( 4.000 :+  0.000) :# L ( 0.000 :+  0.000)) :# B (L ( 0.000 :+  0.000) :# L ( 0.000 :+  0.000)))

Testing input: [ 1.000 :+  0.000,-1.000 :+  0.000, 1.000 :+  0.000,-1.000 :+  0.000]
Expected output: [ 0.000 :+  0.000, 0.000 :+  0.000, 4.000 :+  0.000, 0.000 :+  0.000]
Actual output:   B (B (L ( 0.000 :+  0.000) :# L ( 0.000 :+  0.000)) :# B (L ( 4.000 :+  0.000) :# L ( 0.000 :+  0.000)))

Testing input: [ 1.000 :+  0.000, 0.000 :+  0.000,-1.000 :+  0.000, 0.000 :+  0.000]
Expected output: [ 0.000 :+  0.000, 2.000 :+  0.000, 0.000 :+  0.000, 2.000 :+  0.000]
Actual output:   B (B (L ( 0.000 :+  0.000) :# L ( 2.000 :+  0.000)) :# B (L ( 0.000 :+  0.000) :# L ( 2.000 :+  0.000)))

Testing input: [ 0.000 :+  0.000, 1.000 :+  0.000, 0.000 :+  0.000,-1.000 :+  0.000]
Expected output: [ 0.000 :+  0.000, 0.000 :+ -2.000, 0.000 :+  0.000, 0.000 :+  2.000]
Actual output:   B (B (L ( 0.000 :+  0.000) :# L ( 0.000 :+ -2.000)) :# B (L ( 0.000 :+  0.000) :# L ( 0.000 :+  2.000)))

**Comment by conal** [comment]
Congrats! I merged your circat and lambda-ccc changes and bumped the circat version. You'll want to update from both repos. I'm getting the following error:

```
../test/fft_test.hs:23:8:
    Could not find module ‘Data.Newtypes.PrettyDouble’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```
Yes, I hope that `(&&&)` would inline and simplify fine. I'll go through the code and make some aesthetic suggestions. I like your `inP` idea for starters.

**Comment by capn-freako** [comment]
Ah, yes. You need my *treeviz *package. That's where *PrettyDouble *comes
from.
-db

**Comment by capn-freako** [comment]
*treeviz *is on Hackage.

**Pull request merged**
